repos:
  # --- pre-build ------------------------------------------------------------
  - repo: local
    hooks:
      - id: pyproject2conda
        name: Regenerate Conda env when pyproject.toml changes
        language: python
        entry: hooks/pyproject2conda.py
        additional_dependencies:
          - loguru>=0.7.2
          - pyproject2conda>=0.19.1
        # Only run if the staged diff includes `pyproject.toml`
        files: ^pyproject\.toml$
        # Allow the hook to add/update the YAML file and stage it
        pass_filenames: true

  # --- hygiene --------------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # --- formatting -----------------------------------------------------------
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--safe"]

  # --- linting  -------------------------------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit      # official hook :contentReference[oaicite:1]{index=1}
    rev: v0.4.0
    hooks:
      - id: ruff
        args: ["check", "--fix", "--exit-zero"]

  # --- static typing --------------------------------------------------------
  - repo: local
    hooks:
      - id: mypy
        name: mypy (tox)
        language: python
        entry: tox
        exclude: "^(tests/)|(docs/)|(template/)"
        pass_filenames: false
        args:
          - -e
          - py312-typecheck
        additional_dependencies:
          - tox==4.25.0
          - tox-gh-actions==3.3.0
          - tox-uv==1.25.0
