name: tox PR Tests
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tox:
    name: >-
      ${{ matrix.python-version }} • ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.11"]
        os: ["ubuntu-latest"]

    env:
      TERM: xterm-256color
      PY_COLORS: "1"
      FORCE_COLOR: "1"
      PYTEST_ADDOPTS: "--color=yes"

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Checkout the `able-workflow-copier` repository
        uses: actions/checkout@v4
        with:
          repository: NEU-ABLE-LAB/able-workflow-copier
          ref: 73d06a7fc4d8757fc744cdfbda65dbda018e2324
          path: sandbox/able-workflow-copier

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: able-workflow-rule-copier
          channels: conda-forge, bioconda
          channel-priority: strict
          conda-remove-defaults: "true"
          environment-file: environment-py312-dev.yaml
          miniforge-version: latest

      - name: Setup test suite
        run: tox run-parallel --parallel auto --parallel-no-spinner --notest --skip-missing-interpreters false

      - name: Run tox
        run: tox run-parallel --parallel auto --parallel-no-spinner --skip-pkg-install
